# Paths
bam_root: "/storage/scratch01/groups/md/rnaseq_liver_OBECAN/results/mapped/star"
bam_glob: "/storage/scratch01/groups/md/rnaseq_liver_OBECAN/results/mapped/star/*/Aligned.sortedByCoord.out.bam"

genome_fa: "/storage/scratch01/users/sbarber/Workdir/GRCh38.primary_assembly.genome.fa"
gencode_gtf: "/storage/scratch01/users/sbarber/Workdir/gencode.v38.primary_assembly.annotation.gtf"

# Your helper scripts (as in your workflow)
filter_smorf_pep_py: "/storage/scratch01/users/sbarber/Workdir/filter_smorf_pep.py"
tx_to_genome_py: "/storage/scratch01/users/sbarber/Workdir/smorfs_transcript_to_genome_gtf.py"

# Output directory
outdir: "results_shortstop"

# Threads
threads_stringtie: 8
threads_shortstop: 8
threads_transdecoder: 8   # TransDecoder itself doesn't parallelize much, but kept for resource planning

# smORF filter
min_aa: 10
max_aa: 150